#ifndef REFERENCES_H_INCLUDED
#define REFERENCES_H_INCLUDED

enum Mode {
    MODE_SINGLEPLAYER = 1,
    MODE_MULTIPLAYER
};

enum Direction {
    DIRECTION_STOP = 0,
    DIRECTION_UP,
    DIRECTION_DOWN,
    DIRECTION_LEFT,
    DIRECTION_RIGHT
};

#endif // REFERENCES_H_INCLUDED
